# Setup
title:               Split Learning Project: MIT Media Lab
tagline:             'Split Learning Project: MIT Media Lab'
description:         'Split Learning Project: MIT Media Lab'
url:                 https://splitlearning.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
